meta:
  benchmark_name: "zebralogic_mc"
  split: "test"
  lang: "en"
  input_modality: ["text"]
  output_modality: ["text"]
  task_type: ["unknown"]
  subtask_type: ["reasoning", "multiple_choice"]
dataset:
  source: "huggingface_hub"
  path: "WildEval/ZebraLogic"
  name: "mc_mode"
  split: "test"
prompts:
  direct:
    system_prompt:
    task_prompt: "{}\nAnswer with the option's letter from the given choices directly."
  reasoning:
    system_prompt:
    task_prompt: "{}\nPlease reason step by step, and then answer the question with
      the correct option letter (e.g., A, B, C, D) at the end."
inference:
  generation_options:
    max_new_tokens: 64
postprocess:
  direct:
    pipeline: ['multichoice']
  reasoning:
    pipeline: ['think', 'boxed', 'multichoice']
evaluation:
  method: "generation"
  target_metrics:
    text_evaluator:
      exact_match: {}
  display_metrics: ["exact_match"]
